CREATE TABLE users
(
  id SERIAL NOT NULL UNIQUE,
  email VARCHAR(100) NOT NULL UNIQUE,
  password VARCHAR(100) NOT NULL,
  is_verified BOOLEAN NOT NULL DEFAULT FALSE,
  is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMP WITH TIMEZONE NOT NULL,
  updated_at TIMESTAMP WITH TIMEZONE,
  PRIMARY KEY (id)
);

CREATE TABLE leagues
(
  id SERIAL NOT NULL UNIQUE,
  commissioner_id INT NOT NULL REFERENCES users,
  name TEXT NOT NULL,
  is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMP WITH TIMEZONE NOT NULL,
  updated_at TIMESTAMP WITH TIMEZONE,
  PRIMARY KEY (id)
);

CREATE TABLE seasons
(
  id SERIAL NOT NULL UNIQUE,
  league_id INT NOT NULL REFERENCES leagues,
  starts_at TIMESTAMP WITH TIMEZONE NOT NULL,
  ends_at TIMESTAMP WITH TIMEZONE NOT NULL,
  created_at TIMESTAMP WITH TIMEZONE NOT NULL,
  updated_at TIMESTAMP WITH TIMEZONE,
  PRIMARY KEY (id)
);

CREATE TABLE teams
(
  id SERIAL NOT NULL UNIQUE,
  owner_id INT NOT NULL REFERENCES users,
  season_id INT NOT NULL REFERENCES seasons,
  name TEXT NOT NULL,
  created_at TIMESTAMP WITH TIMEZONE NOT NULL,
  updated_at TIMESTAMP WITH TIMEZONE,
  PRIMARY KEY (id)
);

ALTER TABLE teams ADD UNIQUE (owner_id, season_id);
